In [1]:
# setup
import pandas as pd
import yfinance as yf
import numpy as np
import sys
from pathlib import Path
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))
from src.config import *

In [2]:
from src.data_utils import download_single_ticker

In [3]:
vale = download_single_ticker(
    ticker="VALE3.SA",
    start_date="2020-01-01",
    end_date="2021-01-01"
)

vale.head()

Price           Close       High        Low       Open    Volume
Ticker       VALE3.SA   VALE3.SA   VALE3.SA   VALE3.SA  VALE3.SA
Date
2020-01-02  30.140156  30.201178  29.818394  29.945988  17509700
2020-01-03  29.918255  30.234468  29.724089  29.779565  17284800
2020-01-06  29.740726  29.846130  29.485537  29.846130  32787800
2020-01-07  29.957087  30.062490  29.624231  29.679706  16326400
2020-01-08  29.962637  30.162351  29.746281  30.068043  15298500

In [4]:
import sys
from pathlib import Path
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))
from src.config import *
from src.data_utils import download_multiple_tickers

In [5]:
tickers = [
    "VALE3.SA",
    "PETR4.SA",
    "ITUB4.SA",
    "^BVSP"
]

In [6]:
dados = download_multiple_tickers(
    tickers=tickers,
    start_date="2018-01-01",
    end_date="2025-01-01"
)
dados.keys()

Baixando VALE3.SA...
Baixando PETR4.SA...
Baixando ITUB4.SA...
Baixando ^BVSP...

dict_keys(['VALE3.SA', 'PETR4.SA', 'ITUB4.SA', '^BVSP'])

In [7]:
dados["VALE3.SA"].head()

Price           Close       High        Low       Open    Volume
Ticker       VALE3.SA   VALE3.SA   VALE3.SA   VALE3.SA  VALE3.SA
Date
2018-01-02  21.669315  21.679704  21.004484  21.004484  14156500
2018-01-03  21.539463  21.752416  21.451164  21.726447  12744200
2018-01-04  21.627760  22.006921  21.565433  21.716059  18433000
2018-01-05  21.965370  21.965370  21.456360  21.591403  15251300
2018-01-08  22.453598  22.453598  22.022498  22.022498  14542800

In [8]:
dados["VALE3.SA"].info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1738 entries, 2018-01-02 to 2024-12-30
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   (Close, VALE3.SA)   1738 non-null   float64
 1   (High, VALE3.SA)    1738 non-null   float64
 2   (Low, VALE3.SA)     1738 non-null   float64
 3   (Open, VALE3.SA)    1738 non-null   float64
 4   (Volume, VALE3.SA)  1738 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 81.5 KB

In [10]:
import sys
import pandas as pd
import numpy as np
from pathlib import Path
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))
from src.data_utils import prices_dictionary_to_dataframe
prices = prices_dictionary_to_dataframe(dados)

NameError: name 'pd' is not defined